Merge upstream changes
Vidyard/ruby-pardot pull request #11
Opened 2021-01-22 21:27 UTC by dyroffk

- CustomFields support was added
- Authorization header changes which replace https://github.com/Vidyard/ruby-pardot/pull/10
- Escaping URL entities
- Updated gem dependencies

Merging in upstream changes before adding Salesforce SSO authentication support

2021-01-22 21:34 UTC, avonhatten1996 requested changes
Couple formatting nits then good to go

2021-01-22 21:34 UTC, avonhatten1996 commented on lib/pardot/http.rb
> +
Might want to get rid of these whitespaces

2021-01-22 21:34 UTC, avonhatten1996 commented on spec/support/fakeweb.rb
> +end
Missing the EOF here

2021-01-25 16:46 UTC, dyroffk commented
ok @avonhatten1996 I addressed the comments.  I think I will follow up and add linting to this repo since there were a number of other violations when I ran it locally

I'm going to test this in staging to sanity check the merge went OK

2021-01-25 16:46 UTC, avonhatten1996 approved these changes

2021-01-25 17:38 UTC, karshell approved these changes

2021-01-25 18:02 UTC, bdmubara approved these changes

2021-01-25 19:02 UTC, dyroffk commented
Standby looks like I need to address some differences between `smooth_params_and_headers` and `smooth_params` in this repo vs the upstream.  Ran into a few errors while testing.  Marking blocked until I finish addressing and it's ready for re-review

2021-01-25 19:35 UTC, dyroffk commented
OK this is ready for review again.  I tested end to end in sandbox environment and confirmed working as expected

2021-01-25 19:41 UTC, dyroffk commented
![2021-01-25-144025_2131x538_scrot](https://user-images.githubusercontent.com/440084/105756991-5d5c0700-5f1b-11eb-9ccd-5c73df2d70f4.png)

Fixes included in this changeset address email addresses with special characters failing to create prospects in Pardot

2021-01-25 19:42 UTC, merged